# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_auto_20160620_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='airline name'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='city name'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_number',
            field=models.IntegerField(unique=True, verbose_name='flight number'),
        ),
    ]
